export enum EEpSdkLoggerCodes {
  SERVICE_GET = "SERVICE_GET",
  SERVICE_CREATE = "SERVICE_CREATE",

  TASK_EXECUTE_START = "TASK_EXECUTE_START",
  TASK_EXECUTE_DONE = "TASK_EXECUTE_DONE",
  TASK_EXECUTED_GET = "TASK_EXECUTED_GET",
  TASK_EXECUTED_CREATE = "TASK_EXECUTED_CREATE",
  TASK_EXECUTED_IS_UPDATE_REQUIRED = "TASK_EXECUTED_IS_UPDATE_REQUIRED",
  TASK_EXECUTED_UPDATE = "TASK_EXECUTED_UPDATE",
  TASK_EXECUTED_DELETE = "TASK_EXECUTED_DELETE",
  TASK_EXECUTE_RESULT = "TASK_EXECUTE_RESULT",

  // EXECUTING_TASK_ERROR = "EXECUTING_TASK_ERROR",
  // EXECUTING_TASK_DELETE = "EXECUTING_TASK_DELETE",

}
